version: '3.8'

services:
#  storehouse:
#    build: .
#    container_name: storehouse-app
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
#      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
#      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
#    depends_on:
#      - db
#    volumes:
#      - ./data:/app/data
  db:
    image: postgres:16
    container_name: storehouse-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:3
    container_name: storehouse-localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - LOCALSTACK_DISABLE_TMP_FOLDER=true
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  init-upload:
    image: amazon/aws-cli
    container_name: storehouse-init-upload
    depends_on:
      - localstack
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
    volumes:
      - ./setup-s3-local.sh:/init/setup-s3-local.sh:ro
      - ../src/main/resources/images:/resources/images:ro
    entrypoint: [ "bash", "/init/setup-s3-local.sh" ]

volumes:
  postgres-data:
  localstack-data: