name: Deploy Backend to Oracle VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    uses: diegovaille/deploy-templates/.github/workflows/deploy-docker.yml@v1
    with:
      vm_host: ${{ vars.OCI_VM_HOST }}
      ssh_user: ${{ vars.OCI_VM_SSH_USER }}
      image_name: storehouse-api
      domains: "api.primeira.app.br"
      site_name: backend
      nginx_config_path: deploy/nginx.conf
      container_port: "8080"
      extra_env: |
        SPRING_PROFILES_ACTIVE=prod
        OCI_PRIVATE_KEY_PATH=/root/.oci/oci_api_key.pem
        POSTGRES_USER=${{ vars.POSTGRES_USER }}
        POSTGRES_HOST=${{ vars.POSTGRES_HOST }}
      volume_mounts: "-v /home/ubuntu/.oci:/root/.oci"
    secrets: inherit
